---
stages:
  - name: "lint"
  - name: "test"
  - name: "deploy-github"
    if: "tag IS present"
  - name: "deploy-pypi"
    if: "tag IS present"

language: "python"
python:
  - 3.6
  - 3.7
  - 3.8

env:
  matrix:
    - "NAUTOBOT_VER=1.0.3"
    - "NAUTOBOT_VER=1.1.0"

services:
  - "docker"
# --------------------------------------------------------------------------
# Tests
# --------------------------------------------------------------------------

before_install: >
  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin || travis_terminate 1

before_script:
  - "pip install invoke toml docker-compose poetry"
script:
  - "invoke build --nocache --python-ver $TRAVIS_PYTHON_VERSION"
  - "invoke unittest"

jobs:
  include:
    - stage: "lint"
      before_install: >
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin || travis_terminate 1
      before_script:
        - "pip install invoke toml"
        - "invoke build --nocache"
      script:
        - "invoke black"
        - "invoke bandit"
        - "invoke pydocstyle"
        - "invoke flake8"
        - "invoke yamllint"
        # - "invoke pylint"

    - stage: "deploy-github"
      before_script:
        - "pip install poetry"
      script:
        - "poetry version $TRAVIS_TAG"
        - "poetry build"
      deploy:
        provider: "releases"
        api_key: "$GITHUB_AUTH_TOKEN"
        file_glob: true
        file: "dist/*"
        skip_cleanup: true
        on:  # yamllint disable-line rule:truthy
          all_branches: true

    - stage: "deploy-pypi"
      before_script:
        - "pip install poetry"
      script:
        - "poetry version $TRAVIS_TAG"
        - "poetry config pypi-token.pypi $PYPI_TOKEN"
        - "poetry publish --build"
